### ISSUE TITLE
[FEAT-REQ] Add the lib in the React Native Directory

### ISSUE THREAD

**Issue by rtorrente** [JairajJangle/react-native-visibility-sensor#20]
Hello,

I think it's a good idea to add the library in the React Native Directory. 
Now expo with SDK 52 check all the libs againt this directory to know if they support the newArchitecture and fail with a warning if the lib is not found in the directory.
Check can be disabled for a specific lib but I think it's a good thing to enable it, because add the library in the directory is very easy 

How to : https://github.com/react-native-community/directory/?tab=readme-ov-file#how-do-i-add-a-library

**Comment by JairajJangle** [comment]
Hey there! 👋

Thanks for bringing this up and sharing the link! This definitely sounds like a good idea, especially with Expo SDK 52 checking for libraries in the React Native Directory. I’ll check it out and work on adding the library soon.

Really appreciate you pointing this out! 🙏

**Comment by rtorrente** [comment]
Hey there! 👋

I had to do an MR on the directory, so I added the package at the same time.  : https://github.com/react-native-community/directory/pull/1389

**Comment by JairajJangle** [comment]
Hey there! 👋

Thank you so much for taking the time to raise the PR and for adding the package to the directory! 🎉 I’m really glad to see it’s already been merged. This is super helpful and much appreciated! 🙏

I’ll go ahead and close this issue now. Thanks again for your contribution and support! 😊
